### ISSUE TITLE
Virtual device is marked as unsupported device by IckStream plugin

### ISSUE THREAD

**Issue by WoodsterDK** [philippe44/LMS-Groups#10]
Small bug fix - might not be what is intended, but it works.

Change From:

sub model { "group" }
sub modelName { "Group" }

To: 

sub model { "squeezelite" }
sub modelName { "SqueezeLite" }

**Comment by philippe44** [comment]
you can't do that, it wil break the plugin. it's purposely not a squeezelite

**Comment by WoodsterDK** [comment]
What will break, it seems to be working....

**Comment by philippe44** [comment]
CLI interface won't work (iPeng when it will be made aware of Group Players) and list of players in Plugin settings will include Group Players, which opens the possibility to sync groups with groups and this mess your LMS. It's also probable that more features will depend on the 'model' attribute. And it's fundementally wrong to name it a squeezelite because it's not a squeezelite instance. All my bridges are modified squeezelite so it makes sense there (although I would have preferred to have a different model or at least a modelName) but here it is not. You can do the modification if you want to of course, but it will be overidden at every release I'll do

**Comment by WoodsterDK** [comment]
Ah, ok.
Will see then if Pippin or other IckStream folks can do something.
